"""Phase 6 M6.3B: Provider metadata — reproducibility-critical identity record.

Every field in ProviderMetadata must be sufficient to reproduce or verify any
synthesis output generated by this provider at the time of recording.
"""

from __future__ import annotations

from dataclasses import dataclass

from app.narration.capabilities import ProviderCapabilities, ProviderFeatureFlags


@dataclass(frozen=True)
class ProviderMetadata:
    """Immutable, serialisable identity for a TTS provider integration.

    Captured at registration time and stored alongside every synthesis output.
    Provides enough information to verify or reproduce any generated artifact.

    Fields:
        provider_name       — canonical name used in DB rows (e.g. "fake")
        provider_version    — semver of our integration code (e.g. "0.1.0")
        model_id            — exact model identifier sent in requests
        api_version         — provider API version if declared; None for local
        sdk_name            — SDK or HTTP client used; None for stdlib/no SDK
        sdk_version         — SDK version; None if sdk_name is None
        capabilities        — static capability declaration
        feature_flags       — declared feature support (alias of capabilities.feature_flags)
    """

    provider_name: str
    provider_version: str
    model_id: str
    api_version: str | None
    sdk_name: str | None
    sdk_version: str | None
    capabilities: ProviderCapabilities
    feature_flags: ProviderFeatureFlags

    def to_reproducibility_dict(self) -> dict:
        """Serialise all fields needed to reproduce or verify synthesis output."""
        return {
            "provider_name": self.provider_name,
            "provider_version": self.provider_version,
            "model_id": self.model_id,
            "api_version": self.api_version,
            "sdk_name": self.sdk_name,
            "sdk_version": self.sdk_version,
            "capabilities": self.capabilities.to_dict(),
        }

    def is_local(self) -> bool:
        """True when the provider makes no external calls (sdk_name is None)."""
        return self.sdk_name is None
